# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumslacknegativetest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumslacknegativetest(self):
    self.driver.get("https://app.slack.com/workspace-signin?redir=%2Fgantry%2Fauth%3Fapp%3Dclient%26lc%3D1609421501%26return_to%3D%252Fclient%252FT01FX6E47EG%252FC01FJ9JHHNJ%26teams%3D")
    self.driver.set_window_size(945, 1020)
    self.driver.find_element(By.ID, "domain").send_keys("ResultadosEGC")
    self.driver.find_element(By.CSS_SELECTOR, ".c-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".c-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("PruebasEGC99@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("paraprobar99")
    self.driver.find_element(By.ID, "signin_btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor > p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor > p").send_keys("-estonosesuncomando")
    text = self.driver.find_element(By.CSS_SELECTOR, ".c-message_list > .c-scrollbar__hider").text
    assert text != "Nuevo"
  
